theme = "rose_pine"

[editor]
mouse = true
gutters = ["spacer", "diagnostics", "spacer", "diff"]
auto-save = true
end-of-line-diagnostics = "hint"
true-color = true
shell = ["fish", "-c"]
scrolloff = 10
completion-trigger-len = 1
popup-border = "all"
insert-final-newline = false

[editor.inline-diagnostics]
cursor-line = "error"
other-lines = "disable"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true
max-wrap = 25

[editor.lsp]
display-messages = true
auto-signature-help = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = [
  "diagnostics",
  "selections",
  "position",
  "file-encoding",
  "file-line-ending",
]
separator = "│"
mode.normal = "N"
mode.insert = "I"
mode.select = "S"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
# RIGHT
C-left = ["move_prev_word_start", "trim_selections"]
j = ["move_prev_word_start", "trim_selections"]
# S-j = ":noop"
C-right = ["move_next_word_end", "trim_selections"]
l = ["move_next_word_end", "trim_selections"]
# S-l = ":noop"
up = "move_visual_line_up"
C-up = "move_visual_line_up"
i = "move_visual_line_up"
C-home = "goto_file_start"
S-i = "goto_file_start"
# C-tab = "jump_backward"
C-A-up = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
  "flip_selections",
]  # Move line(s) up
down = "move_visual_line_down"
C-down = "move_visual_line_down"
k = "move_visual_line_down"
C-end = "goto_file_end"
S-k = "goto_file_end"
# C-S-tab = "jump_forward"
C-A-down = [
  "extend_to_line_bounds",
  "delete_selection",
  "paste_after",
  "select_mode",
  "goto_line_start",
  "normal_mode",
]  # Move line(s) down
# u = "undo"
# S-u = ":noop"
C-u = ":noop"
o = ":noop"
# C-o = ":noop"
home = "goto_first_nonwhitespace"
h = "goto_first_nonwhitespace"
# S-h = "redo"
end = "goto_line_end"
";" = "goto_line_end"
# LEFT
pageup = "page_cursor_half_up"
w = "page_cursor_half_up"
S-pageup = "goto_prev_paragraph"
S-w = "goto_prev_paragraph"
A-w = ":noop"
pagedown = "page_cursor_half_down"
s = "page_cursor_half_down"
S-pagedown = "goto_next_paragraph"
S-s = "goto_next_paragraph"
# C-s = ":noop"
A-s = ":noop"
e = "select_regex"
S-e = "split_selection"
# C-e = "goto_previous_buffer"
A-e = "split_selection_on_newline"
# C-d = "goto_next_buffer"
S-x = ["extend_line_up", "extend_to_line_bounds"]

[keys.select]
# RIGHT
C-left = "extend_prev_word_start"
j = "extend_prev_word_start"
# S-j = "extend_to_first_nonwhitespace"
C-right = "extend_next_word_end"
l = "extend_next_word_end"
# S-l = "extend_to_line_end"
up = "extend_visual_line_up"
C-up = "extend_visual_line_up"
i = "extend_visual_line_up"
C-home = "extend_to_file_start"
S-i = "extend_to_file_start"
# C-up = "jump_backward"
C-i = "jump_backward"
A-i = ":noop"
down = "extend_visual_line_down"
C-down = "extend_visual_line_down"
k = "extend_visual_line_down"
C-end = "extend_to_file_end"
S-k = "extend_to_file_end"
C-k = "jump_forward"
A-k = ":noop"
# u = "jump_backward"
# S-u = ":noop"
C-u = ":noop"
# A-u = ":noop"
o = ":noop"
# S-o = ":noop"
# C-o = ":noop"
h = "extend_to_first_nonwhitespace"
# S-h = "redo"
";" = "extend_to_line_end"
# LEFT
pageup = "page_cursor_half_up"
w = "page_cursor_half_up"
S-pageup = "goto_prev_paragraph"
S-w = "goto_prev_paragraph"
A-w = ":noop"
pagedown = "page_cursor_half_down"
s = "page_cursor_half_down"
S-pagedown = "goto_next_paragraph"
S-s = "goto_next_paragraph"
# C-s = ":noop"
A-s = ":noop"
e = "select_regex"
S-e = "split_selection"
C-e = "goto_previous_buffer"
A-e = "split_selection_on_newline"
C-d = "goto_next_buffer"
S-c = ":noop"
A-c = ":noop"
S-x = ["extend_line_up", "extend_to_line_bounds"]

[keys.normal.a]
j = "insert_mode"
left = "insert_mode"
l = "append_mode"
right = "append_mode"
h = "insert_at_line_start"
home = "insert_at_line_start"
";" = "insert_at_line_end"
end = "insert_at_line_end"
i = "open_above"
up = "open_above"
S-up = "open_above"
k = "open_below"
down = "open_below"
S-down = "open_below"
o = "change_selection"
backspace = "change_selection"
S-o = "change_selection_noyank"
S-backspace = "change_selection_noyank"

[keys.select.a]
j = "insert_mode"
left = "insert_mode"
l = "append_mode"
right = "append_mode"
h = "insert_at_line_start"
home = "insert_at_line_start"
";" = "insert_at_line_end"
end = "insert_at_line_end"
i = "open_above"
up = "open_above"
k = "open_below"
down = "open_below"
o = "change_selection"
backspace = "change_selection"
S-o = "change_selection_noyank"
S-backspace = "change_selection_noyank"

[keys.normal.b]
r = [":reload-all", ":redraw"]
s = ":write-all!"
b = "buffer_picker"
i = "goto_previous_buffer"
k = "goto_next_buffer"
c = ":write-buffer-close"
S-c = ":write-buffer-close!"
A-c = ":buffer-close-others"
x = ":buffer-close-all"

[keys.select.b]
r = [":reload-all", ":redraw"]
s = ":write-all!"
b = "buffer_picker"
i = "goto_previous_buffer"
k = "goto_next_buffer"
c = ":write-buffer-close"
S-c = ":write-buffer-close!"
A-c = ":buffer-close-others"
x = ":buffer-close-all"

[keys.normal.c]
a = "code_action"
k = "hover"
c = "toggle_comments"
e = "rename_symbol"
x = ":write-quit-all!"
q = ":q!"
f = "goto_file"
d = "goto_definition"
S-d = "goto_declaration"
y = "goto_type_definition"
r = "goto_reference"
s = "symbol_picker"
h = "select_references_to_symbol_under_cursor"

[keys.select.c]
a = "code_action"
k = "hover"
c = "toggle_comments"
e = "rename_symbol"
x = ":write-quit-all!"
q = ":q!"
f = "goto_file"
d = "goto_definition"
S-d = "goto_declaration"
y = "goto_type_definition"
r = "goto_reference"
s = "symbol_picker"
h = "select_references_to_symbol_under_cursor"

[keys.normal.f]
j = "find_prev_char"
left = "find_prev_char"
l = "find_next_char"
right = "find_next_char"
S-j = "till_prev_char"
S-left = "till_prev_char"
S-l = "find_till_char"
S-right = "find_till_char"

[keys.select.f]
j = "find_prev_char"
left = "find_prev_char"
l = "find_next_char"
right = "find_next_char"
S-j = "till_prev_char"
S-left = "till_prev_char"
S-l = "find_till_char"
S-right = "find_till_char"

[keys.normal.t]
d = "goto_next_diag"
S-d = "goto_last_diag"
g = "goto_next_change"
S-g = "goto_last_change"
f = "goto_next_function"
t = "goto_next_class"
S-t = "goto_next_test"
a = "goto_next_parameter"
c = "goto_next_comment"
e = "goto_next_entry"
y = "goto_next_tabstop"
i = "add_newline_above"
k = "add_newline_below"

[keys.select.t]
d = "goto_next_diag"
S-d = "goto_last_diag"
g = "goto_next_change"
S-g = "goto_last_change"
f = "goto_next_function"
t = "goto_next_class"
S-t = "goto_next_test"
a = "goto_next_parameter"
c = "goto_next_comment"
e = "goto_next_entry"
y = "goto_next_tabstop"
i = "add_newline_above"
k = "add_newline_below"

[keys.normal.T]
d = "goto_prev_diag"
S-d = "goto_first_diag"
g = "goto_prev_change"
S-g = "goto_first_change"
f = "goto_prev_function"
t = "goto_prev_class"
S-t = "goto_prev_test"
a = "goto_prev_parameter"
c = "goto_prev_comment"
e = "goto_prev_entry"
y = "goto_prev_tabstop"
i = "add_newline_above"
k = "add_newline_below"

[keys.select.T]
d = "goto_prev_diag"
S-d = "goto_first_diag"
g = "goto_prev_change"
S-g = "goto_first_change"
f = "goto_prev_function"
t = "goto_prev_class"
S-t = "goto_prev_test"
a = "goto_prev_parameter"
c = "goto_prev_comment"
e = "goto_prev_entry"
y = "goto_prev_tabstop"
i = "add_newline_above"
k = "add_newline_below"

[keys.normal.Z]
s = ["move_prev_word_start", "trim_selections"]
f = ["move_next_word_end", "trim_selections"]
e = "move_visual_line_up"
S-e = "page_cursor_half_up"
d = "move_visual_line_down"
S-d = "page_cursor_half_down"

[keys.normal.space]
r = [":config-reload", ":redraw"]
f = "file_picker_in_current_directory"
S-f = "file_picker_in_current_buffer_directory"
e = "file_explorer_in_current_buffer_directory"
S-e = ":noop"
";" = ":sh hxe filetree \"$(realpath '%{buffer_name}')\""
c = ":noop"
S-c = ":noop"
A-c = ":noop"

[keys.normal.space.x]
";" = ":sh hxe filetree \"$(realpath '%{buffer_name}')\""
"/" = ":sh hxe find-replace \"$(realpath '%{buffer_name}')\""
t = ":sh hxe terminal"

[keys.select.space]
r = [":config-reload", ":redraw"]
f = "file_picker_in_current_directory"
S-f = "file_picker_in_current_buffer_directory"
e = "file_explorer_in_current_buffer_directory"
c = ":noop"
S-c = ":noop"
A-c = ":noop"
