[[language]]
name = "toml"
formatter = { command = "prettier" }
auto-format = true

[[language]]
name = "yaml"
formatter = { command = "prettier" }
auto-format = true

[[language]]
name = "typescript"
injection-regex = "(ts|typescript)"
file-types = ["ts", "mts", "cts"]
# @see https://github.com/helix-editor/helix/discussions/8452#discussioncomment-12224231
formatter = { command = "npx", args = ["prettier", "--parser", "typescript"] }
auto-format = true

[[language]]
name = "javascript"
language-servers = [
  "typescript-language-server",
  "eslint-lsp",
]  # ADD eslint-lsp to your langauge.
# formatter = { command = 'prettier', args = ['--parser', 'babel'] }
auto-format = false
