[[language]]
name = "toml"
formatter = { command = "prettier" }
auto-format = true

[[language]]
name = "yaml"
formatter = { command = "prettier" }
auto-format = true

[[language]]
name = "typescript"
injection-regex = "(ts|typescript)"
file-types = ["ts", "mts", "cts"]
auto-format = false
formatter = { command = "npx", args = ["prettier", "--parser", "typescript"] }

[[language]]
name = "javascript"
language-servers = [
  "typescript-language-server",
  "eslint-lsp",
]
auto-format = false

[[language]]
name = "ini"
scope = "source.ini"
file-types = [
  "ini",
  # Systemd unit files
  "service",
  "automount",
  "device",
  "mount",
  "path",
  "service",
  "slice",
  "socket",
  "swap",
  "target",
  "timer",
  # Podman quadlets
  "container",
  "volume",
  "kube",
  "network",
  { glob = ".editorconfig" },
  { glob = "rclone.conf" },
  "properties",
  "cfg",
  "directory",
  "conf",
]
injection-regex = "ini"
comment-token = "#"
indent = { tab-width = 4, unit = "\t" }

# C# configuration
[[language]]
name = "c-sharp"
auto-format = true
language-servers = ["omnisharp"]

[[grammar]]
name = "ini"
source = { git = "https://github.com/justinmk/tree-sitter-ini", rev = "87176e524f0a98f5be75fa44f4f0ff5c6eac069c" }

[language-server.omnisharp]
command = "OmniSharp"
args = ["--languageserver"]

[language-server.omnisharp.config]
FormattingOptions.EnableEditorConfigSupport = true
RoslynExtensionsOptions.EnableAnalyzersSupport = true
RoslynExtensionsOptions.EnableImportCompletion = true
RoslynExtensionsOptions.AnalyzeOpenDocumentsOnly = false
