#!/bin/bash
FILE=$1
MESSAGE=$(cat "$FILE")
BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "")

TICKET=$(
  echo "$BRANCH" |
  grep -Eo '[A-Za-z]+[-][0-9]+' |
  tr "[:lower:]" "[:upper:]" |
  sed 's/.*\(.*\)/[\0]/' |
  tr -d '\n'
)

if [[ -z "$TICKET" || "$MESSAGE" == "$TICKET"* ]]; then
  exit 0
fi

echo "$TICKET $MESSAGE" > "$FILE"
